version: "3"

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    container_name: oracle
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "1521:1521"
      - "22:22"
  redis:
    image: redis:latest
    restart: always
    container_name: redis-server
    ports:
      - "6379:6379"
